# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b24ec871db026f13fc81bcb8778ab50bfe872da3e14599cc1c128b20c2808153dcdd23b3acc52c5cbdb9b76efc4ea0bc60e130ae958733cd573b1c3d63ed45

test:
  secret_key_base: 73e58ed59dbc268049820acb077c08dd0e6be4f62c46fbd5bb7d4b26b757142b5192cbcd059b1c1e91a19cfca6662c319133e9907e5b366492e3f8a6aea1dfb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
